config/routes.rb
Rails.application.routes.draw do
    resources :favorites, only: [:create, :destroy]
    namespace :account do
        resources :orders, :favorites, only: [:index]
        # resources :profiles, only: [:show, :edit, :update]
        get 'profiles/:username', to: 'profiles#show', as: :profile
        get 'profiles/:username/edit', to: 'profiles#edit', as: :edit_profile
        patch 'profiles/:username/edit', to: 'profiles#update', as: :update_profile
    end

    namespace :admin do
        resources :categories
        resources :products
        resources :orders do
            member do
                post :cancel
                post :ship
                post :deliver
                post :return
            end
        end
    end

    devise_for :users, controllers: { confirmations: 'confirmations' }
    root 'welcome#home'
    get 'change' => 'welcome#change'
    get 'about' => 'welcome#about'
    get 'sail' => 'welcome#sail'
    resources :products do
        member do
            post :add_to_cart
        end
    end

    resources :carts do
        collection do
            delete :clean
            post :checkout
        end
    end
    resources :cart_items
    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :apply_to_cancel
        end
    end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.create(product: product)
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity* cart_item.product.price
      end
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "Cart emptied!"
    redirect_to products_path
  end

  def checkout
    @order = Order.new
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/views/carts/checkout.html.erb
  <div class="container">
<div class="row">



  <div class="col-md-12">
    <h2>Order details</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">Product Details</th>
          <th>Price</th>
          <th>Quantity</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td><%= link_to(cart_item.product.title, product_path(cart_item.product)) %></td>
            <td><%= cart_item.product.price %></td>
            <td><%= cart_item.quantity %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="total clearfix">
      <span class="pull-right">
        Total <%= render_cart_total_price(current_cart) %> USD
      </span>
    </div>
    <h2> Order Info</h2>
    <div class="order-form">
      <%= simple_form_for @order do |f| %>
        <legend>Purchaser</legend>
        <div class="form-group col-lg-6"><%= f.input :billing_name %></div>
        <div class="form-group col-lg-6"><%= f.input :billing_address %></div>
        <div class="form-group col-lg-6"><%= f.input :shipping_name %></div>
        <div class="form-group col-lg-6"><%= f.input :shipping_address %></div>
        <div class="checkout">
          <%= f.submit "Order", class: "btn btn-lg btn-danger pull-right", data: {disable_with: "Submitting..."} %>
        </div>
      <% end %>
    </div>
  </div>
</div>
  </div>

app/views/carts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to("Empty Cart", clean_carts_path, method: :delete, class: "pull-right", style: "text_decoration: underline;", data: {confirm: "Are you sure to empty the cart?"}) %>
    <h2>Shopping Cart</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product Info</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Modify</th>
        </tr>
        <tbody>
          <% current_cart.cart_items.each do |cart_item| %>
            <tr>
              <td>
                <%= link_to product_path(cart_item.product) do %>
                  <% if cart_item.product.image.present? %>
                    <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail") %>
                  <% else %>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to(cart_item.product.title, product_path(cart_item.product)) %></td>
              <td><%= cart_item.product.price %></td>
              <td>
                <% cart_item = current_cart.cart_items.find_by(product_id: cart_item.product_id) %>
                <%= form_for cart_item, url: cart_item_path(cart_item.product.id) do |f|%>
                  <%= f.select :quantity, 1..cart_item.product.quantity %>
                  <%= f.submit "Update", data: {disable_with: "Submitting..."} %>
                <% end %>
              </td>
              <td>
                <%= link_to(fa_icon("trash", text: "Delete"), cart_item_path(cart_item.product_id), method: :delete) %>
              </td>
            </tr>
          <% end %></tbody>
      </thead>
    </table>
    <br>
    <div class="total clearfix">
      <span class="pull-right">
        <span>Total <%= render_cart_total_price(current_cart) %> USD</span>
      </span>
    </div>
    <hr>
    <div class="checkout clearfix">
      <%= link_to("Checkout", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>