config/routes.rb
Rails.application.routes.draw do
    resources :favorites, only: [:create, :destroy]
    namespace :account do
        resources :orders, :favorites, only: [:index]
        # resources :profiles, only: [:show, :edit, :update]
        get 'profiles/:username', to: 'profiles#show', as: :profile
        get 'profiles/:username/edit', to: 'profiles#edit', as: :edit_profile
        patch 'profiles/:username/edit', to: 'profiles#update', as: :update_profile
    end

    namespace :admin do
        resources :categories
        resources :products
        resources :orders do
            member do
                post :cancel
                post :ship
                post :deliver
                post :return
            end
        end
    end

    devise_for :users, controllers: { confirmations: 'confirmations' }
    root 'welcome#home'
    get 'change' => 'welcome#change'
    get 'about' => 'welcome#about'
    get 'sail' => 'welcome#sail'
    resources :products do
        member do
            post :add_to_cart
        end
    end

    resources :carts do
        collection do
            delete :clean
            post :checkout
        end
    end
    resources :cart_items
    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :apply_to_cancel
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :favorites
  has_many :fans, through: :favorites, source: :user
  belongs_to :category

  validates :title, :description, :quantity, :category, :price, presence: true
  validates :quantity, :price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    layout 'admin'

    before_action :authenticate_user!
    before_action :admin_required

    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)

        if @product.save
            redirect_to admin_products_path
        else
            render :new
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])

        if @product.update(product_params)
            redirect_to admin_products_path
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        @cart = current_cart
        @cart_item = @cart.cart_items.find_by(product_id: params[:id])
        if @cart_item.blank?
            redirect_to admin_products_path, alert: 'Product deleted successfully.'
        else
            @cart_item.destroy
            redirect_to admin_products_path, alert: 'Product deleted successfully.'
        end
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.order("id DESC")
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).paginate(page: params[:page], per_page: 6) #Product.order("id DESC")#
    @categories.each do |c|
        instance_variable_set("@products_#{c.id}", Product.where(category_id: c.id))
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
    current_cart.add_product_to_cart(@product)
    flash[:notice] = "Add #{@product.title} to shopping cart successful"
    else
      # TODO: add one 1 to quantity
      flash[:warning] = "#{@product.title} is already in your cart!"
    end
    redirect_to :back
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_product_image(product)
    if product.image.present?
      link_to(image_tag(product.image.thumb.url),product_path(product), class: "thumbnail")
    else
      link_to(image_tag("http://placehold.it/200x200&text=No Image"), product_path(product),class:"thumbnail")
    end
  end
end

app/views/products/index.html.erb
<div class="header1" style="background-image: url(https://ww1.sinaimg.cn/large/006tKfTcgy1fd7l0zipjsj31bu0giwgx.jpg)">
  <div class="container">
              <div class="row">
                  <div class="col-lg-12 col-md-12 bounceInLeft">
                      <h1 class=" fadeInUp wow text-center"><span class="huge "> 2 </span>周时间，行动效能提升<span class="huge ">5</span>倍</h1>
                      <p class="text-center">降低试错成本，让成长实现弯道超车</p>
                  </div>
              </div>
              </div>
</div>
<div class="container">
  <div class="content">
    <div class="banner">
      <div class="spacing-top">
        <h1><span class="lead">《超级行动训练营》即将起航！
          <hr>
        </span>即刻登船，到知识的海洋里打捞宝藏。</h1>
        <p>课程开放日期：3月21日开课，即日起即可报名</p>
        <h1>课程时间安排</h1>
        <p>3月20日第1课：成为超级行动派的秘密</p>
        <p>3月23日第2课：如何制定一份马上就能用的计划</p>
        <p>3月27日第3课：让你弯道超车的魔鬼进步公式</p>
        <p>3月30日第4课：阶段性爆破增值路径提取</p>
        <p>上课时间地点：线上微信群统一直播听课</p>
        <p>注意：本课程为系列课程，点开任意一个Part购买即可，不需要重复购买。</p>
        <h1 class="text-center text-success">购买时请点击下方商品图片</h1>
      </div>
    </div>
    <%#= render "carousel" %>
    <div class="category-bar">
      <div class="spacing-top">
        <div class="search">
          <%= search_form_for @q, :builder => SimpleForm::FormBuilder, class:"search_form" do |f| %>
            <!-- <%= f.label :Search, class: "h2"%> -->
            <div class="search_form_content">
              <%= f.search_field :title_or_description_cont, placeholder: "请在此输入搜索内容", class: "search_field" %>
            </div>
            <div class="search_form_button">
              <%= f.submit "search",class: "btn btn-lg btn-info" %>
            </div>
          <% end %>
        </div>
      </div>
      <!-- nav-tabs -->
      <div class="spacing-top">
        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="all" href="#home">All</a></li>
          <% @categories.each do |c|%>
            <li><a data-toggle="tab" href="#<%= c.id %>"><%= c.name %></a> </li>
          <% end %>
        </ul>
      </div>
      <!-- End nav-tabs -->
      <div class="spacing-top">
        <!-- tab-content -->
        <div class="tab-content">
          <!-- first tab -->
          <div class="tab-pane fade in active" id="home">
            <div class="content-md col-md-12" style="text-center;">
              <div class="row">
                <% @products.each do |product| %>
                  <div class="col-xs-10 col-sm-6 col-md-6" style="margin-bottom: 30px;">
                    <%= render_product_image(product) %>
                    <%= product.title %>
                    <% if current_user %>
                    <span class="pull-right">
                    <% if current_user.favorites.where(product: product).empty? %>
                    <%= link_to("收藏", favorites_path(product_id: product), method: :post) %>
                    <% else %>
                    <%= link_to("取消收藏", favorite_path(product), method: :delete) %>
                    <% end %></span>
                    <% end %>
                  </div>
                <% end %>
                <div class=" text-center" style="padding-bottom: 30px;">
                  <div class="digg_pagination">
                    <%= will_paginate @products, previous_label: "前一页", next_label: "后一页", page_links: false%>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- next tab_s -->
          <% @categories.each do |c| %>
            <div class="tab-pane fade" id="<%= c.id %>">
              <div class="content-md col-md-12" style="text-center;">
                <div class="row">
                  <% instance_variable_get("@products_#{c.id}").each do |product| %>
                    <div class="col-xs-10 col-sm-6 col-md-6 col-lg-6" style="margin-bottom: 30px;">
                      <%= render_product_image(product) %>
                      <%= product.title %>
                      <% if current_user %>
                      <span class="pull-right">
                      <% if current_user.favorites.where(product: product).empty? %>
                      <%= link_to("收藏", favorites_path(product_id: product), method: :post) %>
                      <% else %>
                      <%= link_to("取消收藏", favorite_path(product), method: :delete) %>
                      <% end %></span>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class=" text-center" style="padding-bottom: 30px;">
          <div class="digg_pagination">
            <%= will_paginate @products, previous_label: "前一页", next_label: "后一页", page_links: false%>
          </div>
        </div>
        <!-- End tab-content -->
      </div>
    </div>
  </div>
  <div class="text-center ">
    <br><br><br>
      <%= link_to("去“一定要看”瞅瞅",change_path, class:"btn btn-lg btn-success") %>
    <hr>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-9">
      <% if @product.image.present? %>
        <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
      <% else %>
        <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
      <% end %>
    </div>
    <div class="col-md-3">
      <h2><%= @product.title %></h2>
      <div style="height:100px;">
        <p><%= @product.description %></p>
      </div>
      <div class="product-price"> $ <%= @product.price %>
      </div>
      <div class="pull-right">
        <% if @product.quantity.present? && @product.quantity > 0 %>
          <%= link_to("买票上船", add_to_cart_product_path(@product), method: :post, class: "btn btn-primary btn-lg btn-danger") %>
        <% else %>
          Sold out!
            <br>
          <%= link_to("Add to Cart", "#", class: "btn btn-primary btn-lg btn-danger disabled" ) %>
        <% end %>
      </div>
    </div>
  </div>
</div>