config/routes.rb
Rails.application.routes.draw do
    resources :favorites, only: [:create, :destroy]
    namespace :account do
        resources :orders, :favorites, only: [:index]
        # resources :profiles, only: [:show, :edit, :update]
        get 'profiles/:username', to: 'profiles#show', as: :profile
        get 'profiles/:username/edit', to: 'profiles#edit', as: :edit_profile
        patch 'profiles/:username/edit', to: 'profiles#update', as: :update_profile
    end

    namespace :admin do
        resources :categories
        resources :products
        resources :orders do
            member do
                post :cancel
                post :ship
                post :deliver
                post :return
            end
        end
    end

    devise_for :users, controllers: { confirmations: 'confirmations' }
    root 'welcome#home'
    get 'change' => 'welcome#change'
    get 'about' => 'welcome#about'
    get 'sail' => 'welcome#sail'
    resources :products do
        member do
            post :add_to_cart
        end
    end

    resources :carts do
        collection do
            delete :clean
            post :checkout
        end
    end
    resources :cart_items
    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :apply_to_cancel
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.create(product: product)
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity* cart_item.product.price
      end
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_lists
  belongs_to :user

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :delivered
    state :order_cancelled
    state :good_returned

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipping
    end

    event :deliver do
      transitions from: :shipping, to: :delivered
    end

    event :return_good do
      transitions from: :delivered, to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :favorites
  has_many :fans, through: :favorites, source: :user
  belongs_to :category

  validates :title, :description, :quantity, :category, :price, presence: true
  validates :quantity, :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  attr_accessor :login
  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  has_many :orders
  has_many :favorites
  has_many :favorite_products, through: :favorites, source: :product

  def admin?
    is_admin
  end

  has_attached_file :avatar, styles: { medium: '152x152#' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "Cart emptied!"
    redirect_to products_path
  end

  def checkout
    @order = Order.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save
      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end
      current_cart.clean!
      OrderMailer.notify_order_placed(@order).deliver!

      redirect_to order_path(@order.token), notice: "Order placed, please pay with either alipay or wechat"
    else
      render 'carts/checkout'
    end
  end

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  def pay_with_alipay
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用支付宝付款成功"
  end

  def pay_with_wechat
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用微信付款成功"
  end

  def apply_to_cancel
    @order = Order.find(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请取消订单"
    redirect_to :back
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice]= "敬请期待！"
  end

  def home

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_avatar_select(user)
    if user.avatar.exists?
      image_tag @user.avatar.url(:medium),
                id: 'image-preview',
                class: 'img-responsive img-circle profile-image'
    else
      image_tag 'default-avatar.jpg', id: 'image-preview',
                                      class: 'img-responsive img-circle profile-image'
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES={alert:"danger", notice:"success", warning:"warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已完成付款"
    else
      "尚未完成付款"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_product_image(product)
    if product.image.present?
      link_to(image_tag(product.image.thumb.url),product_path(product), class: "thumbnail")
    else
      link_to(image_tag("http://placehold.it/200x200&text=No Image"), product_path(product),class:"thumbnail")
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key,msg| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        Copyright &copy;2017
        <%= fa_icon("ship", text: "Designed by") %>
        <%= link_to("Zion & 乌龙明月", "http://zion.logdown.com") %>

      </div>
      <div class="foot-link">
        <%= link_to(fa_icon("weibo", text: "官方微博"),"https://fullstack.xinshengdaxue.com/works/194") %>

      </div>
      <div class="foot-link">
        <%= link_to(fa_icon("wechat", text: "微信公号"),"https://fullstack.xinshengdaxue.com/works/194") %>
      </div>
      <div class="foot-link">
        <%= link_to(fa_icon("question", text: "常见问题"),"https://fullstack.xinshengdaxue.com/works/194") %>
      </div>
      <div class="foot-link">
        <%= link_to(fa_icon("comments", text: "联系我们"),"https://fullstack.xinshengdaxue.com/works/194") %>
      </div>
      <div class="foot-link">
        <%= link_to(fa_icon("info", text: "关于我们"),"https://fullstack.xinshengdaxue.com/works/194") %>
      </div>
      <br>
    </div>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-hearder">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><%= image_tag("pirate_icon.png", size:"32") %></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><%= link_to("最新航程", products_path) %></li>
                <li><%= link_to("一定要看", change_path) %></li>
                <li><%= link_to("关于我们", about_path) %></li>
                <li><%= link_to("奇迹论坛", sail_path) %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if current_cart.products.any? %>
                    <li>
                        <%= link_to cart_path(current_cart) do %>
                            <%= fa_icon("shopping-cart", text: "Cart", right: true) %>(<%= current_cart.products.count %>)
                        <% end %>
                    </li>
                <% end %>
                <% if !current_user %>
                    <li><%= link_to(fa_icon("user-plus", text: "Sign Up"), new_user_registration_path) %></li>
                    <li><%= link_to(fa_icon("sign-in", text: "Login"), new_user_session_path) %></li>
                <% else %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Hi!, <%= current_user.email %>
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <% if current_user.admin? %>
                                <li>
                                    <%= link_to("Admin Panel", admin_products_path) %>
                                </li>
                            <% else %>
                            <li><%= link_to('Profile', account_profile_path(current_user.username)) %></li>
                            <li><%= link_to("Order History", account_orders_path) %></li>
                            <li><%= link_to("My Favorites", account_favorites_path) %></li>
                            <% end %>
                            <li class="devider" role="separator"></li>
                            <li><%= link_to(fa_icon("sign-out", text: "Logout"), destroy_user_session_path, method: :delete) %></li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JDstore Admin Panel</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container content">
      <%= render "common/navbar" %>
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
            <li><%= link_to("Product", admin_products_path) %></li>
            <li><%= link_to("Orders", admin_orders_path) %></li>
            <li><%= link_to("Categories", admin_categories_path) %></li>
          </ul>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "common/footer" %>
  </body>
  <%= js add_gritter(flash[:notice],image: :notice, title: "海盗学院：", sticky: false), extend_gritter(position: :bottom_right) %>
</html>
<script>new WOW().init();</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title> Pirate College</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div class="contaner content">
            <%= render "common/navbar" %>
            <%= yield %>
        </div>
        <%= render "common/footer" %>
    </body>
    <%= js add_gritter(flash[:notice],image: :notice, title: "海盗学院：", sticky: false), extend_gritter(position: :bottom_right) %>
</html>
<script>new WOW().init();</script>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>JDStoreMg</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div id="login" class="login">
            <div class="container content">
                <%= render "common/navbar" %>
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 wow flipInY" data-wow-delay="1.2s">
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <%= render "common/footer" %>
    </body>
    <%= js add_gritter(flash[:notice],image: :notice, title: "Pirate College Notification", sticky: false), extend_gritter(position: :bottom_right) %>
    <%=  %>
</html>
<script>new WOW().init();</script>